export default {
  WHITE: '#ffffff',
  BLACK: '#000',
  TEXT_BLACK: '#333333',
  TEXT_WHITE: '#ffffff',
  DARK_GREY: '#2b2b2b',
  YELLOW: '#cfab57',
  LIGHT_GREY: '#e6e6e6',
  DIVIDER: '#efefef',
  REDBLACK: '#CB0500',
  RED: '#EE2A2F',
  ORANGE: '#EE813A',
  YELLOWBLACK: '#EEAB2A',
  GREEN: '#0ac93d',
};
