export default {
  // BASE_URL: 'http://192.168.18.6/finalproject_laravel/public',
  BASE_URL: 'https://pinterusmedia.com',
  login: '/api/login',
  register: '/api/register',
  profile: '/api/profile',
  ewarong: '/api/ewarong',
  alldistricts: '/api/alldistrics',
  allvillages: '/api/allvillages',
  allitems: '/api/allitems',
  orders: '/api/orderuser',
  myorders: '/api/getorderbyuser',
  todaychartuser: '/api/todaychartuser',
  adminreport: '/api/adminreport',
  confirmorder: '/api/confirmorder',
  finishorder: '/api/finishorder',
  rejectedorder: '/api/rejectedorder',
  confirmewarong: '/api/confirmewarong',
  profileImageUrl: '/user/profile/',
  updateProfile: '/api/updateprofile',
};
